// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: delete_all_users.sql

package database

import (
	"context"
)

const deleteAllUsers = `-- name: DeleteAllUsers :exec
DELETE FROM users WHERE id IN (SELECT id FROM users)
RETURNING id, created_at, updated_at, email
`

func (q *Queries) DeleteAllUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllUsers)
	return err
}
