// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: get_chirp_by_id.sql

package database

import (
	"context"
)

const getChirpByID = `-- name: GetChirpByID :one
SELECT id, body, user_id, created_at, updated_at FROM chirps
WHERE id = $1
`

func (q *Queries) GetChirpByID(ctx context.Context, id string) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, getChirpByID, id)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.Body,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
