// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: update_chirpy_red_user.sql

package database

import (
	"context"
	"database/sql"
)

const updateChirpyRedUser = `-- name: UpdateChirpyRedUser :one
UPDATE users SET is_chirpy_red = $1
WHERE id = $2
RETURNING id, created_at, updated_at, email, hashed_password, is_chirpy_red
`

type UpdateChirpyRedUserParams struct {
	IsChirpyRed sql.NullBool
	ID          string
}

func (q *Queries) UpdateChirpyRedUser(ctx context.Context, arg UpdateChirpyRedUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateChirpyRedUser, arg.IsChirpyRed, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}
